- name:  Install docker on EC2
  hosts: ec2
  gather_facts: true
  become: yes
  tasks:
    - name: Install Docker using DNF
      dnf:
        name: docker
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to the Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

