name: Deploy Frontend to Cloudflare Pages

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Upload Node Modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: frontend/node_modules

  lint-check:
    name: Lint Check
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Download Node Modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: frontend/node_modules

      - name: Run Lint Check
        run: |
          cd frontend
          npm install
          npm run lint:check

  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Node Modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: frontend/node_modules

      - name: Run Format Check
        run: |
          cd frontend
          npm install
          npm run format:check

  build:
    name: Build Vue.js App
    runs-on: ubuntu-latest
    needs: [lint-check, format-check]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Node Modules
        uses: actions/download-artifact@v4
        with:
          name: node_modules
          path: frontend/node_modules

      - name: Build Vue.js App
        run: |
          cd frontend
          npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "monorepo-ci-cd"
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          directory: frontend/dist